
# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sampleTwiter_development


test:
  <<: *default
  database: sampleTwiter_test


#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: sampleTwiter_production
  username: sampleTwiter
  password: <%= ENV['SAMPLETWITER_DATABASE_PASSWORD'] %>
